name: Sync docker images

on:
  workflow_dispatch:
  schedule:
    # run each 8h
    - cron: "0 */8 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Update skopeo
        run: |
          sudo apt-get update
          sudo apt-get -y install skopeo
      - name: Skopeo version
        run: skopeo --version
      - name: Skopeo login
        env:
          HUAWEI_U: ${{ secrets.HUAWEI_U }}
          HUAWEI_P: ${{ secrets.HUAWEI_P }}
          ALI_U: ${{ secrets.ALI_U }}
          ALI_P: ${{ secrets.ALI_P }}
          GITHUB_U: ${{ secrets.TOKEN_GITHUB_U }}
          GITHUB_P: ${{ secrets.TOKEN_GITHUB_P }}
        run: |
          skopeo login --username $HUAWEI_U --password $HUAWEI_P swr.cn-north-4.myhuaweicloud.com
          skopeo login --username $ALI_U --password $ALI_P registry.cn-hangzhou.aliyuncs.com
          skopeo login --username $GITHUB_U --password $GITHUB_P ghcr.io

      - name: Skopeo Sync
        run: |
          skopeo sync --scoped -a -s yaml -d docker 2hw.yml swr.cn-north-4.myhuaweicloud.com/bxb100
          skopeo sync -a -s yaml -d docker 2al.yml registry.cn-hangzhou.aliyuncs.com/bxb100
